### ISSUE TITLE
Default behaviour hidden

### ISSUE THREAD

**Issue by islamadel** [bdemirkir/sidebar_hide#42] opened 2016-03-16 15:15 UTC
How can I make the default status of sidebar to be hidden?

**Comment by bdemirkir** [comment] 2016-03-16 15:38
I didn't want to be invasive. So, by default, it's not hidden. If you want to make it hidden by default, you can change [this line](https://github.com/bdemirkir/sidebar_hide/blob/master/app/views/sidebar/_hideButton_partial.html.erb#L8) to something like this:
```<% if !cookies["sidebar_hide"] %>```

I didn't test this. Please use it with caution.

**Comment by islamadel** [comment] 2016-03-16 15:54
Thanks, but it didn't work, now sidebar is always visible

**Comment by bdemirkir** [comment] 2016-03-16 16:52
How about this: ```<% if !cookies["sidebar_hide"]? %>```

**Comment by islamadel** [comment] 2016-03-16 17:07
This causes an error

`Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

`

**Comment by bdemirkir** [comment] 2016-03-17 08:20
Well, I don't have my RoR dev environment right now. Until I add that new feature, you may want to fiddle with that line. That's the place you can make it happen. I'll add this feature to my todo list.

**Comment by bdemirkir** [comment] 2016-03-17 08:26
Duplicate of issue #25

**Closed by bdemirkir** 2016-03-17 08:26 UTC
Labels: todo
